# Generated by Django 4.1.4 on 2022-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_created_date_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(null=True, to='store.variation'),
        ),
    ]
