# Generated by Django 4.1.4 on 2022-12-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_variation_product_product_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
