# Generated by Django 4.1.4 on 2022-12-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catImage',
        ),
    ]
