# Generated by Django 4.1.5 on 2023-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catImage',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
